# Generated by Django 5.1 on 2024-09-26 20:29

import grades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_rename_max_points_assignment_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[grades.models.is_positive]),
        ),
    ]
